# Generated by Django 2.2.1 on 2019-06-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190604_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
