# Generated by Django 2.2.1 on 2019-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190604_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actor', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(related_name='director', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
